spring.application.name=StockControl2

#message
spring.messages.basename=i18n/messages,i18n/validationMessages


#DataSource
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.encoding=UTF-8
#データベースの初期化について設定する(alwaysは常に初期化を実行する).
spring.sql.init.mode=ALWAYS
#データベースの初期テーブル構造を記述したファイル（及びディレクトリ）を指定(CREATE TABLE IF NOT EXISTS にしているため,同名のテーブルが存在すれば作成しない).
spring.sql.init.schema-locations=classpath:schema.sql
#データベースの初期データを記述したファイル（及びディレクトリ）を指定.
spring.sql.init.data-locations=classpath:data.sql

#H2DB
spring.h2.console.enabled=true

#MyBatis p125.138.
mybatis.mapper-locations=classpath*:/mapper/sql/*.xml
mybatis.configuration.map-underscore-to-camel-case=true 
mybatis.type-aliases-package=com.example.domain.*.model,com.example.dto.*

#Log Level.
logging.level.com.example=debug

# 1つのファイルの最大アップロードサイズを設定する(デジタルカメラでの撮影を考慮して20MBに設定している).
spring.servlet.multipart.max-file-size=20MB
# 1つのリクエスト全体の最大サイズを設定する.
# 画像ファイル自体は20MB以下だがリクエスト全体が20MBをこえると接続を切るため,すこし余裕をもたせている.
spring.servlet.multipart.max-request-size=25MB

# リクエストサイズ制限を超えた際にサーバーがどれだけのデータを読み捨て（受け取ってすぐ捨てる）てから接続を閉じるかの最大値を指定する.
# 20MBをこえる画像ファイルが来たときTomcatはデフォルトで2MBまで,つまり20MBをこえた2MB分までなら読み捨てしてくれるが,
# 接続を強制的に切断するため設定していたエラー画面に遷移せず,
# ブラウザ側の接続できていないことを示す画面に遷移する.
# そのためこれを設定することで,この設定値までは読み捨てるという余裕を持たせることで設定していたエラー画面に遷移できるようにする.
# -1に設定すると無制限に読み捨てるが,大きいファイルを読み続けることで通信の占有されてしまったり,
# わざと大きいファイルをおくることでサーバーをパンクさせるDoS攻撃（拒否攻撃）にあったりするため設定している.
#server.tomcat.max-swallow-size=2MB

# 画像保存先（任意）.
file.upload-dir=C:/Users/user/uploads/products/
