spring.application.name=StockControl2

#message
spring.messages.basename=i18n/messages,i18n/validationMessages

#DataSource
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.encoding=UTF-8
#データベースの初期化について設定する(alwaysは常に初期化を実行する).
spring.sql.init.mode=ALWAYS
#データベースの初期テーブル構造を記述したファイル（及びディレクトリ）を指定(CREATE TABLE IF NOT EXISTS にしているため,同名のテーブルが存在すれば作成しない).
spring.sql.init.schema-locations=classpath:schema.sql
#データベースの初期データを記述したファイル（及びディレクトリ）を指定.
spring.sql.init.data-locations=classpath:data.sql

#H2DB
spring.h2.console.enabled=true

#MyBatis p125.138.
mybatis.mapper-locations=classpath*:/mapper/sql/*.xml
mybatis.configuration.map-underscore-to-camel-case=true 
mybatis.type-aliases-package=com.example.domain.*.model,com.example.dto.*

#Log Level.
logging.level.com.example=debug

# 1つのファイルの最大アップロードサイズを設定する.
spring.servlet.multipart.max-file-size=30MB

# 1つのリクエスト全体の最大サイズを設定する.
spring.servlet.multipart.max-request-size=35MB

# 画像保存先（任意）.
file.upload-dir=C:/Users/user/uploads/products/
