spring.application.name=StockControl2

#message.
spring.messages.basename=i18n/messages,i18n/validationMessages

#MySQL の接続 URL.タイムゾーン（?serverTimezone=JST）はいらなくなった()
#spring.datasource.url=jdbc:mysql://localhost:3306/stock?serverTimezone=Asia/Tokyo
#MySQL にアクセスするためのユーザー名.
#spring.datasource.username=root
#MySQL にアクセスするユーザーのパスワード.
#spring.datasource.password=root
#JDBC ドライバのクラス名 com.mysql.cj.jdbc.Driver を指定する.
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Spring Boot がアプリケーション起動時に実行するSQLスクリプト（schema.sqlやdata.sqlなど）の文字エンコーディングを指定する設定プロパティ.
#spring.sql.init.encoding=utf-8

#DataSource
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.encoding=UTF-8
#データベースの初期化について設定する(alwaysは常に初期化を実行する).
spring.sql.init.mode=ALWAYS
#データベースの初期テーブル構造を記述したファイル（及びディレクトリ）を指定(CREATE TABLE IF NOT EXISTS にしているため,同名のテーブルが存在すれば作成しない).
spring.sql.init.schema-locations=classpath:schema.sql
#データベースの初期データを記述したファイル（及びディレクトリ）を指定.
spring.sql.init.data-locations=classpath:data.sql

#H2DB
spring.h2.console.enabled=true


#MyBatis p125.138.
mybatis.mapper-locations=classpath*:/mapper/sql/*.xml
mybatis.configuration.map-underscore-to-camel-case=true 
mybatis.type-aliases-package=com.example.domain.*.model,com.example.dto.*

#Log Level.
logging.level.com.example=debug

# 1つのファイルの最大アップロードサイズを設定する(デジタルカメラでの撮影を考慮して20MBに設定している).
spring.servlet.multipart.max-file-size=20MB
# 1つのリクエスト全体の最大サイズを設定する.
spring.servlet.multipart.max-request-size=40MB

# アップロードされたファイルが一時ファイルとして保存されるしきい値(閾値)を設定している.
#(しきい値未満のファイルはメモリに保持され,それ以上の場合はOS一時ディレクトリに保存).
spring.servlet.multipart.file-size-threshold=1MB

# 画像保存先（任意）META-INFにJSONがあるが補完してるだけ(絶対パスをいれている).
file.upload-dir=./uploads

# Whitelabelエラー画面を無効化（自作エラー画面を使うため）.
server.error.whitelabel.enabled=false
